## Example of relationship graph

In [26]:
import numpy as np

kolduny = np.array([[0, .2, .7, .8 ], [0, .3, .7, .5], [.5, .5, .5, .5], [.7, .4, .4, .6 ], [.7, .7, .3, .3]])
wizardss = np.array([[0, 0.3, 0.3, 0.7, 0], [0.3, 0.1, 0.7, 0.3, 0.8], [0.8, 0.6, 0.5, 0.4, 0.3], [0.8, 0.8, 0.5, 0.6, 0.2]])

print("Kolduny")
print(kolduny)
print("Wizards")
print(wizardss)
z = [] 
for x1 in kolduny:
    for y1 in wizardss.T:
        z.append(max(np.multiply(x1, y1)))
print("\nRow -kolduny, Coloum - wizards\n")
print(z)

Kolduny
[[ 0.   0.2  0.7  0.8]
 [ 0.   0.3  0.7  0.5]
 [ 0.5  0.5  0.5  0.5]
 [ 0.7  0.4  0.4  0.6]
 [ 0.7  0.7  0.3  0.3]]
Wizards
[[ 0.   0.3  0.3  0.7  0. ]
 [ 0.3  0.1  0.7  0.3  0.8]
 [ 0.8  0.6  0.5  0.4  0.3]
 [ 0.8  0.8  0.5  0.6  0.2]]

Row -kolduny, Coloum - wizards

[0.64000000000000012, 0.64000000000000012, 0.40000000000000002, 0.47999999999999998, 0.20999999999999999, 0.55999999999999994, 0.41999999999999998, 0.34999999999999998, 0.29999999999999999, 0.23999999999999999, 0.40000000000000002, 0.40000000000000002, 0.34999999999999998, 0.34999999999999998, 0.40000000000000002, 0.47999999999999998, 0.47999999999999998, 0.29999999999999999, 0.48999999999999994, 0.32000000000000006, 0.23999999999999999, 0.23999999999999999, 0.48999999999999994, 0.48999999999999994, 0.55999999999999994]


In [ ]:
Группа А Количество Группа Б Количество
Костянной дракон 1 Крестьяне 2 
Ведьмы 2 Феи 4
Вампиры 3 Эльфы 3 
Зомби 5 Крестьяне 5
Скелеты 8 Эльфы 8 


In [65]:

index, value = max(enumerate(new), key=operator.itemgetter(1))
print("Костянной дракон", value)
wNew = [0 for x in range(5)]
for x in range(0, 4):
        wNew[x]=wizards[x,index]
index1, value1 = min(enumerate(wNew), key=operator.itemgetter(1))
if(index1==0):
    print("Крестьяне:", value1)

Костянной дракон 0.7
Крестьяне: 0.0
